dist: xenial

language: python

sudo: true

addons:
  apt:
    packages:
      - xvfb

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install tox-travis
  - python -m pip install -r requirements.test

script:
  - python setup.py bdist_wheel
  - tox -vvvvvvvvv
